# Generated by Django 4.1.4 on 2023-02-23 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='', verbose_name='Avatar Image')),
                ('mobile_phone', models.CharField(max_length=11, verbose_name='Mobile Number')),
                ('email', models.EmailField(max_length=254, verbose_name='User Email')),
                ('label', models.CharField(max_length=50, verbose_name='Label')),
                ('person_name', models.CharField(max_length=50, verbose_name='Person Name')),
                ('last_updated', models.DateField(verbose_name='Last Updated')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'ContactBook',
                'verbose_name_plural': 'ContactBook',
            },
        ),
    ]
